[workspace]
members = [
    "crates/kapsl-cli",
]
exclude = [
    "patches/esaxx-rs",
]

resolver = "2"

[patch.crates-io]
esaxx-rs = { path = "patches/esaxx-rs" }
kapsl-backends = { git = "https://github.com/kapsl-runtime/kapsl-sdk.git", rev = "2e2e4d93fdaf54dcc2e85b39e78740d78454e18f" }
kapsl-core = { git = "https://github.com/kapsl-runtime/kapsl-sdk.git", rev = "2e2e4d93fdaf54dcc2e85b39e78740d78454e18f" }
kapsl-engine-api = { git = "https://github.com/kapsl-runtime/kapsl-sdk.git", rev = "2e2e4d93fdaf54dcc2e85b39e78740d78454e18f" }
kapsl-hal = { git = "https://github.com/kapsl-runtime/kapsl-sdk.git", rev = "2e2e4d93fdaf54dcc2e85b39e78740d78454e18f" }
kapsl-ipc = { git = "https://github.com/kapsl-runtime/kapsl-sdk.git", rev = "2e2e4d93fdaf54dcc2e85b39e78740d78454e18f" }
kapsl-llm = { git = "https://github.com/kapsl-runtime/kapsl-sdk.git", rev = "2e2e4d93fdaf54dcc2e85b39e78740d78454e18f" }
kapsl-monitor = { git = "https://github.com/kapsl-runtime/kapsl-sdk.git", rev = "2e2e4d93fdaf54dcc2e85b39e78740d78454e18f" }
kapsl-rag = { git = "https://github.com/kapsl-runtime/kapsl-sdk.git", rev = "2e2e4d93fdaf54dcc2e85b39e78740d78454e18f" }
kapsl-rag-sdk = { git = "https://github.com/kapsl-runtime/kapsl-sdk.git", rev = "2e2e4d93fdaf54dcc2e85b39e78740d78454e18f" }
kapsl-scheduler = { git = "https://github.com/kapsl-runtime/kapsl-sdk.git", rev = "2e2e4d93fdaf54dcc2e85b39e78740d78454e18f" }
kapsl-shm = { git = "https://github.com/kapsl-runtime/kapsl-sdk.git", rev = "2e2e4d93fdaf54dcc2e85b39e78740d78454e18f" }
kapsl-transport = { git = "https://github.com/kapsl-runtime/kapsl-sdk.git", rev = "2e2e4d93fdaf54dcc2e85b39e78740d78454e18f" }
llama-cpp-2 = { git = "https://github.com/kapsl-runtime/kapsl-sdk.git", rev = "2e2e4d93fdaf54dcc2e85b39e78740d78454e18f" }
llama-cpp-sys-2 = { git = "https://github.com/kapsl-runtime/kapsl-sdk.git", rev = "2e2e4d93fdaf54dcc2e85b39e78740d78454e18f" }
